language: python

env:
  global:
    - AWS_BUCKET="oanhnn/terraform-aws"
    # - AWS_KEY
    # - AWS_SECRET

install:
  - pip install yamllint
  - pip install awscli
  - pip install cfn-lint

script:
  - yamllint .
  - find . -type f -name *.yml | while read file; do set -ex && cfn-lint -i E2520 -t "$file"; done;

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      find . -type f -name *.yml | while read file; do set -ex && aws s3 cp "$file" "s3://$AWS_BUCKET/oanhnn-aws-cf/$TRAVIS_COMMIT/$file" && aws cloudformation validate-template --template-url "https://s3.amazonaws.com/$AWS_BUCKET/oanhnn-aws-cf/$TRAVIS_COMMIT/$file" > /dev/null; done;

    fi
  - if [[ ! -z "$TRAVIS_TAG" ]]; then
    docker tag $DOCKER_REPO:$BUILD_TAG $DOCKER_REPO:$TRAVIS_TAG;
    docker push $DOCKER_REPO:$TRAVIS_TAG;
    fi
