---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create common infrastructure

Parameters:

  Environment:
    Description: Environment to deploy. Use staging for limited resources and no alerts.
    Type: String
    AllowedValues:
      - Staging
      - Production
    Default: Staging

  TemplateBucket:
    Description: The S3 Bucket containing AWS CloudFormation template directory.
    Type: String
    MinLength: 1
    MaxLength: 255
    Default: oanhnn-aws-cfn

  TemplateKey:
    Description: The S3 Key for AWS CloudFormation template directory.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[A-Za-z0-9+-_]+(/[A-Za-z0-9+-_]+)*$
    Default: master/templates

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.0.0/16
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.10.0/24
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.11.0/24
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.20.0/24
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.21.0/24
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  DataSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the data subnet in the first Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.30.0/24
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  DataSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the data subnet in the second Availability Zone
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    Default: 10.10.31.0/24
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28

  S3BucketName:
    Description: The name of the S3 bucket for uploading files.
    Type: String
    Default: ''

  DBSnapshot:
    Description: The identifier for the DB cluster snapshot from which you want to restore (leave blank to create an empty cluster).
    Type: String
    Default: ''

  DBInstanceType:
    Description: The instance type of database server.
    Type: String
    AllowedValues:
      - db.t2.small
      - db.t2.medium
      - db.t2.xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    Default: db.t2.small

  DBName:
    Description: The name of the database (ignored when DBSnapshotIdentifier is set, value used from snapshot).
    Type: String
    Default: ''

  DBUsername:
    Description: The master user name for the DB instance (ignored when DBSnapshotIdentifier is set, value used from snapshot).
    Type: String
    Default: dbadmin

  DBPassword:
    Description: The master password for the DB instance (ignored when DBSnapshotIdentifier is set, value used from snapshot).
    Type: String
    NoEcho: true
    Default: ''

  # See https://docs.aws.amazon.com/AmazonElastiCache/latest/UserGuide/CacheNodes.SelectSize.html
  CacheNodeType:
    Description: Cache node instance class, e.g. cache.t2.micro (free tier)
    Type: String
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
    Default: cache.t2.micro
    ConstraintDescription: Node instance class not supported.

  NumCacheNodes:
    Description: The number of cache nodes.
    Type: Number
    MinValue: 1
    MaxValue: 5
    Default: 2
    ConstraintDescription: The number of nodes on group must be between 1 and 5.

  AlertEmail:
    Description: The email address that will receive alerts.
    Type: String

  AlertFallbackEmaill:
    Description: The email address that will receive alerts if alerts can not be delivered.
    Type: String
    Default: ''

  LogsRetentionInDays:
    Description: Specifies the number of days you want to retain log events.
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

  SSHFrom:
    Description: Limit SSH access to bastion instance from a CIDR block address.
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Default: 0.0.0.0/0

  KeyName:
    Description: 'Optional key pair of the ec2-user to establish a SSH connection to the SSH bastion host/instance.'
    Type: AWS::EC2::KeyPair::KeyName
    Default: ''

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Parameters
        Parameters:
          - Environment
          - TemplateBucket
          - TemplateKey

      - Label:
          default: Infrastructure Parameters
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - DataSubnet1CIDR
          - DataSubnet2CIDR

      - Label:
          default: S3 Parameters
        Parameters:
          - S3BucketName

      - Label:
          default: RDS Parameters (MySQL)
        Parameters:
          - DBSnapshot
          - DBInstanceType
          - DBName
          - DBUsername
          - DBPassword

      - Label:
          default: ElastiCache Parameters (Redis)
        Parameters:
          - CacheNodeType
          - NumCacheNodes

      - Label:
          default: Operations Parameters
        Parameters:
          - AlertEmail
          - AlertFallbackEmaill
          - SSHFrom
          - LogsRetentionInDays

Conditions:

  IsProduction: !Equals [!Ref Environment, Production]

Resources:

  AlertStack:
    Condition: IsProduction
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/alert.cfn.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        Email: !Ref AlertEmail
        FallbackEmail: !Ref AlertFallbackEmaill

  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/vpc.cfn.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        Environment: !Ref Environment
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        DataSubnet1CIDR: !Ref DataSubnet1CIDR
        DataSubnet2CIDR: !Ref DataSubnet2CIDR

  S3BucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/s3-bucket.cfn.yml
      Parameters:
        BucketName: !Ref S3BucketName
        Access: 'CloudFrontRead'
        Versioning: 'false'
        NoncurrentVersionExpirationInDays: '0'
        Encryption: 'false'

  S3EndpointStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/s3-endpoint.cfn.yml
      Parameters:
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PrivateRouteTables:
          Fn::If:
            - IsProduction
            - !Join [',', [!GetAtt VpcStack.Outputs.PrivateRouteTable1, !GetAtt VpcStack.Outputs.PrivateRouteTable2]]
            - !GetAtt VpcStack.Outputs.PrivateRouteTable1
        S3Bucket: !GetAtt S3BucketStack.Outputs.Bucket

  ClientSGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/client-sg.cfn.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  BastionStack:
    Condition: IsProduction
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/bastion.cfn.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        AlertTopicARN: !If [IsProduction, !GetAtt AlertStack.Outputs.TopicARN, !Ref 'AWS::NoValue']
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        PublicSubnets: !GetAtt VpcStack.Outputs.PublicSubnets
        KeyName: !Ref KeyName
        IAMUserSSHAccess: 'true'
        SystemsManagerAccess: 'true'
        InstanceType: 't2.nano'
        LogsRetentionInDays: !Ref LogsRetentionInDays
        SSHFrom: !Ref SSHFrom

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/aurora-mysql.cfn.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        AlertTopicARN: !If [IsProduction, !GetAtt AlertStack.Outputs.TopicARN, !Ref 'AWS::NoValue']
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        DataSubnets: !GetAtt VpcStack.Outputs.DataSubnets
        BastionSecurityGroup: !If [IsProduction, !GetAtt BastionStack.Outputs.SecurityGroup, !Ref 'AWS::NoValue']
        ClientSecurityGroup: !GetAtt ClientSGStack.Outputs.SecurityGroup
        DBSnapshot: !Ref DBSnapshot
        DBInstanceType: !Ref DBInstanceType
        DBName: !Ref DBName
        DBUsername: !Ref  DBUsername
        DBPassword: !Ref DBPassword
        DBBackupRetentionPeriod: '30'
        DBEncryption: 'false'

  CacheStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/${TemplateKey}/elasticache-redis.cfn.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        AlertTopicARN: !If [IsProduction, !GetAtt AlertStack.Outputs.TopicARN, !Ref 'AWS::NoValue']
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        DataSubnets: !GetAtt VpcStack.Outputs.DataSubnets
        BastionSecurityGroup: !If [IsProduction, !GetAtt BastionStack.Outputs.SecurityGroup, !Ref 'AWS::NoValue']
        ClientSecurityGroup: !GetAtt ClientSGStack.Outputs.SecurityGroup
        CacheNodeType: !Ref CacheNodeType
        NumCacheNodes: !Ref NumCacheNodes
        AutoMinorVersionUpgrade: 'true'

Outputs:

  StackName:
    Description: Stack Name
    Value: !Ref AWS::StackName
