---
AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Security Group to allow client may be access some services

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    MaxLength: 30
    MinLength: 1
    AllowedPattern: ^[A-Za-z0-9]*$
    ConstraintDescription: Must contain only alphanumeric characters and numbers.

  VpcId:
    Description: The VPC ID.
    Type: AWS::EC2::VPC::Id

Resources:

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Client Security Group
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ClientSecurityGroup

Outputs:

  StackName:
    Description: Stack Name
    Value: !Sub ${AWS::StackName}

  SecurityGroup:
    Description: The Client Security Group
    Value: !Ref SecurityGroup
